### ISSUE TITLE
Impossible to train a XGBoost model

### ISSUE THREAD

**Issue by egolep** [alan-turing-institute/MLJXGBoostInterface.jl#11]
Anytime I try to fit a model, I keep getting the same error:

got unsupported keyword argument "label"

and this happens in the DMatrix call.

Looking directly to XGBoost.jl repo, they actually use DMatrix with the label argument, so is it a version problem between the MLJ interface and XGBoost.jl or am I missing something?

**Comment by egolep** [comment]
The problem was missing values in the dataset.
Not very intuitive from the error message, but still a problem of mine.

Forgive me

**Comment by ablaom** [comment]
Curious as to how you could present missing values without a scitype warning being raised. I would have expected a complaint about data `input_scitype` being incompatible with the model `input_sciype`. Are you not constructing a machine, perhaps?

If you can provide reproducible example, I can try to improve the error reporting.
