### ISSUE TITLE
Not possible to set nthread  parameter in MLJXGBoostInterface.XGBoostRegressor()

### ISSUE THREAD

**Issue by dmahasen** [alan-turing-institute/MLJXGBoostInterface.jl#12]
Hi,

I was trying to set the number of threads to use in fitting XGBoost Regression model. But it seems that `MLJXGBoostInterface.XGBoostRegressor()` does not accept `nthread `  argument though underling `xgboost()` function in XGBoost.jl  has  `nthread `  argument to limit the number of threads to use in model fitting.

I would be grateful to have this feature. #XGBoost

Thank you,

Mahasen Dehideniya

**Comment by ablaom** [comment]
Sounds like a good idea. If you have the expertise, I would be happy to expedite a PR to expose `nthread`.

**Comment by dmahasen** [comment]
I made the required changes. #13. :)
