### ISSUE TITLE
Issue to tag new releases

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJXGBoostInterface.jl#5]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
cc @AttilaKovacs @jbrea @Moelf @pgagarinov

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- [x] Expose the `nthread` hyper-parameter in all models (#12 #13) @dmahasen

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**breaking**) Re-implement the `save` and `restore` methods supporting serialization, to address MLJ API changes at https://github.com/JuliaAI/MLJBase.jl/pull/733. These changes are not backwards compatible: to restore models serialised using MLJXGBoostInterface < 0.2, you will need a version of MLJXGBoostInterface < 0.2 loaded. 

- Bump minimum Julia requirement to 1.6

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Reorganize code for better maintenance and make adjustments for major overhaul of XGBoost.jl, 2.0. 
- Fix  `save` method to create persistent representations of learned parameters that avoid file I/O.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ExpandingMan** [comment]
I just registered 0.3.1 via juliahub successfully but tagbot did not trigger.... somehow wherever I go tagbot does not work, perhaps it doesn't work if you do it through juliahub?

**Comment by ablaom** [comment]
Yeah, that's weird. I don't really get it. 

I usually tag via [a pinned issue](https://github.com/JuliaAI/MLJXGBoostInterface.jl/issues/5), which I have in each repo and that appears to also kick TagBot into action.

**Comment by ablaom** [comment]
https://github.com/JuliaAI/MLJXGBoostInterface.jl/actions/runs/3482666232

**Comment by ablaom** [comment]
That get's a green light but actually errors?

**Comment by ablaom** [comment]
@DilumAluthge Be great if you could pitch in here.

How do we get TagBot to issue a tag after registration when it doesn't happen automatically (for reasons we don't understand)? I've just kicked TagBot in gh action and that's giving a [green light](https://github.com/JuliaAI/MLJXGBoostInterface.jl/actions/runs/3482666232) but still no tag. I see there is a warning logged, but I don't know what it means ("server error"). We're at 0.3.1 on General

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
Just to confirm  that TagBot still works for me when I trigger release from here.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by rikhuijzer** [comment]
@JuliaRegistrator register branch=master

Release notes:

This release restricts XGBoost version to <2.5 because newer XGBoost versions cause the MLJXGBoostInterface to crash.

**Comment by rikhuijzer** [comment]
@JuliaRegistrator register

Release notes:

Allow newer XGBoost versions again after the previous release. Thanks to XGBoost for fixing the problem at their side.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Expose xgboost's `early_stopping_rounds::Int` hyperparameter (#50)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Add support for per-observation weights (#56)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Expose the XGBoost hyperparameter `monotone_constraints` (#58)
