### ISSUE TITLE
Update latest release with early stopping rounds to MLJ

### ISSUE THREAD

**Issue by matthew-liu-1** [alan-turing-institute/MLJXGBoostInterface.jl#51]
Can we please tag the latest release with changes made in #50?

**Comment by ablaom** [comment]
Thanks for flagging. I've just bumped the version and noticed that tests are failing on Julia 1.10. So that will need investigating.

**Comment by ablaom** [comment]
There is an RNG instability in recently added tests.

**Comment by ablaom** [comment]
https://github.com/JuliaAI/MLJXGBoostInterface.jl/pull/52

**Comment by ablaom** [comment]
https://github.com/JuliaRegistries/General/pull/110181

**Comment by matthew-liu-1** [comment]
Awesome - thanks @ablaom
